# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170108_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
